sudo: required
services:
    - docker

before_install:
    - docker build -t shashi1/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true USERNAME/react-test npm test

after_success:
    - docker build -t shashi1/multi-client -f ./client
    - docker build -t shashi1/multi-nginx ./nginx
    - docker build -t shashi1/multi-server ./server
    - docker build -t shashi1/multi-worker ./worker
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push shashi1/multi-client
    - docker push shashi1/mulit-nginx
    - docker push shashi1/multi-server
    - docker push shashi1/multi-worker
